sudo: false

language: php

cache:
  directories:
  - $HOME/.composer/cache

env:
  global:
  - COMPOSER_ARGS="--no-interaction"

matrix:
  include:
  - php: 7.0
  - php: 7.1
  - php: 7.2
  - php: 8.0
  - php: 8.1
    env:
    - CS_CHECK=true
    - TEST_COVERAGE=true

before_install:
- if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
- travis_retry composer install $COMPOSER_ARGS --ignore-platform-reqs
- stty cols 120 && composer show

script:
- if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
- if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi

after_script:
- if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry php vendor/bin/php-coveralls -v ; fi